version: '3.7'

services:
  apache:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    environment:
      MYSQL_HOST: mysql-db
      MYSQL_DATABASE: disastercloud
      MYSQL_USER: disastercloud
      MYSQL_PASSWORD: 9)=B=qcZ@/E:hMtR
    command: 
      - bash 
      - -c
      - |
        chmod -R 777 *
        composer install
        exec apache2-foreground
    networks:
      - disastercloud

  mysql-db:
    build:
      context: .
      dockerfile: Dockerfile-mysql
    volumes:
      - disastercloud-db-data:/va/lib/mysql
    environment:
      MYSQL_DATABASE: disastercloud
      MYSQL_USER: disastercloud
      MYSQL_PASSWORD: 9)=B=qcZ@/E:hMtR
      MYSQL_ROOT_PASSWORD: m@XbCC~h4/PD>5D8
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - disastercloud

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql-db
    ports:
      - "8080:80"
    networks:
      - disastercloud
networks:
  disastercloud:
volumes:
  disastercloud-db-data: